{{
  config(
    materialized='view',
    tags=['bit_live', 'events', 'staging']
  )
}}

select
    cast(event_id as varchar) as event_id,
    cast(version as varchar) as version,
    cast(artist_event_id as varchar) as artist_event_id,
    cast(artist_event_int_id as integer) as artist_event_int_id,
    cast(title as varchar) as title,
    cast(use_custom_title as boolean) as use_custom_title,
    cast(description as varchar) as description,
    cast(media_id as integer) as media_id,
    tags,
    cast(artist_id as integer) as artist_id,
    cast(artist_name as varchar) as artist_name,
    cast(artist_verified as boolean) as artist_verified,
    cast(artist_media_id as integer) as artist_media_id,
    artist_genres,
    cast(artist_tracker_count as integer) as artist_tracker_count,
    cast(artist_on_tour as boolean) as artist_on_tour,
    cast(artist_stamp as varchar) as artist_stamp,
    cast(show_multi_ticket as boolean) as show_multi_ticket,
    lineup,
    lineup_names,
    manager_tickets,
    tickets,
    bandsintown_tickets,
    cast(first_manager_ticket_type as varchar) as first_manager_ticket_type,
    cast(num_collected_tickets as integer) as num_collected_tickets,
    cast(num_managed_tickets as integer) as num_managed_tickets,
    cast(venue_id as varchar) as venue_id,
    cast(venue_name as varchar) as venue_name,
    cast(venue_location as varchar) as venue_location,
    cast(venue_address as varchar) as venue_address,
    cast(venue_city as varchar) as venue_city,
    cast(venue_region as varchar) as venue_region,
    cast(venue_country as varchar) as venue_country,
    cast(venue_country_iso_code as varchar) as venue_country_iso_code,
    cast(venue_postal_code as varchar) as venue_postal_code,
    cast(venue_latlong as varchar) as venue_latlong,
    cast(venue_latitude as double) as venue_latitude,
    cast(venue_longitude as double) as venue_longitude,
    cast(venue_timezone as varchar) as venue_timezone,
    cast(venue_deleted as varchar) as venue_deleted,
    cast(venue_modification_date as varchar) as venue_modification_date,
    cast(rsvp_count as integer) as rsvp_count,
    cast(on_sale_date_time as varchar) as on_sale_date_time,
    cast(announcement_date_time as varchar) as announcement_date_time,
    cast(last_modified_time as varchar) as last_modified_time,
    cast(starts_at as varchar) as starts_at,
    cast(starts_at_gmt as varchar) as starts_at_gmt,
    cast(cutover_datetime_gmt as varchar) as cutover_datetime_gmt,
    cast(ends_at as varchar) as ends_at,
    cast(datetime_display_rule as varchar) as datetime_display_rule,
    cast(venue_media_id as integer) as venue_media_id,
    cast(widget_visible as boolean) as widget_visible,
    cast(streaming_event as boolean) as streaming_event,
    cast(streaming_url as varchar) as streaming_url,
    cast(streaming_service_type as varchar) as streaming_service_type,
    cast(streaming_service_name as varchar) as streaming_service_name,
    cast(streaming_service_logo as varchar) as streaming_service_logo,
    subscription_types,
    cast(embeddable as boolean) as embeddable,
    festival_names,
    festival_ids,
    cast(testing_artist as boolean) as testing_artist,
    cast(playback_status as varchar) as playback_status,
    cast(subscription_channel as varchar) as subscription_channel,
    cast(bandsintown_plus as boolean) as bandsintown_plus,
    cast(chat_channel_id as varchar) as chat_channel_id,
    cast(bandsintown_ticket as boolean) as bandsintown_ticket,
    cast(sold_out as boolean) as sold_out,
    cast(free as boolean) as free,
    presale,
    cast(has_tickets as boolean) as has_tickets,
    cast(promoted as boolean) as promoted,
    tracking
from {{ source('bit_live', 'events_batch_v2') }}

