Resources:
  MWAAExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - airflow-env.amazonaws.com
                - airflow.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /service-role/

  MWAAExecutionPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Roles:
        - !Ref MWAAExecutionRole
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action: airflow:PublishMetrics
            Resource:
              - !Sub "arn:aws:airflow:${AWS::Region}:${AWS::AccountId}:environment/bit-dbt"
          - Effect: Deny
            Action: s3:ListAllMyBuckets
            Resource: "*"
          - Effect: Allow
            Action:
              - s3:GetObject*
              - s3:GetBucket*
              - s3:List*
            Resource:
              - !Sub "arn:aws:s3:::${self:custom.vars.airflow_environment_bucket_name}"
              - !Sub "arn:aws:s3:::${self:custom.vars.airflow_environment_bucket_name}/*"
          - Effect: Allow
            Action:
              - logs:CreateLogStream
              - logs:CreateLogGroup
              - logs:PutLogEvents
              - logs:GetLogEvents
              - logs:GetLogRecord
              - logs:GetLogGroupFields
              - logs:GetQueryResults
              - logs:DescribeLogGroups
            Resource: "*"
          - Effect: Allow
            Action: cloudwatch:PutMetricData
            Resource: "*"
          - Effect: Allow
            Action:
              - sqs:ChangeMessageVisibility
              - sqs:DeleteMessage
              - sqs:GetQueueAttributes
              - sqs:GetQueueUrl
              - sqs:ReceiveMessage
              - sqs:SendMessage
            Resource:
              - !Sub "arn:aws:sqs:${AWS::Region}:*:airflow-celery-*"
          - Effect: Allow
            Action:
              - kms:Decrypt
              - kms:DescribeKey
              - kms:GenerateDataKey*
              - kms:Encrypt
            NotResource: !Sub "arn:aws:kms:*:${AWS::AccountId}:key/*"
            Condition:
              StringLike:
                kms:ViaService:
                  - !Sub "sqs.${AWS::Region}.amazonaws.com"
          - Effect: Allow
            Action:
              - glue:GetDatabase
              - glue:GetDatabases
              - glue:CreateDatabase
              - glue:GetTable
              - glue:GetTables
              - glue:CreateTable
              - glue:UpdateTable
              - glue:DeleteTable
              - glue:GetPartition
              - glue:GetPartitions
              - glue:CreatePartition
              - glue:BatchCreatePartition
              - glue:DeletePartition
              - glue:BatchDeletePartition
            Resource:
              - !Sub "arn:aws:glue:${AWS::Region}:${AWS::AccountId}:catalog"
              - !Sub "arn:aws:glue:${AWS::Region}:${AWS::AccountId}:database/*"
              - !Sub "arn:aws:glue:${AWS::Region}:${AWS::AccountId}:table/*/*"
          - Effect: Allow
            Action:
              - athena:StartQueryExecution
              - athena:GetQueryExecution
              - athena:GetQueryResults
              - athena:StopQueryExecution
              - athena:GetWorkGroup
            Resource:
              - !Sub "arn:aws:athena:${AWS::Region}:${AWS::AccountId}:workgroup/primary"
          - Effect: Allow
            Action:
              - s3:GetObject*
              - s3:PutObject*
              - s3:DeleteObject*
              - s3:GetBucket*
              - s3:List*
            Resource:
              - "arn:aws:s3:::bit-bigdata-daily-state-cycle"
              - "arn:aws:s3:::bit-bigdata-daily-state-cycle/*"
              - !Sub "arn:aws:s3:::${self:custom.vars.airflow_environment_bucket_name}"
              - !Sub "arn:aws:s3:::${self:custom.vars.airflow_environment_bucket_name}/*"

  MWAAEnvironment:
    Type: AWS::MWAA::Environment
    Properties:
      Name: bit-dbt
      SourceBucketArn: !Sub "arn:aws:s3:::${self:custom.vars.airflow_environment_bucket_name}"
      ExecutionRoleArn: !GetAtt MWAAExecutionRole.Arn
      DagS3Path: dags
      NetworkConfiguration:
        SecurityGroupIds: ${self:custom.vars.vpc.securityGroupIds}
        SubnetIds: ${self:custom.vars.vpc.subnetIds}
      WebserverAccessMode: PRIVATE_ONLY
      MaxWorkers: 1
      MinWorkers: 1
      RequirementsS3Path: requirements.txt

