Resources:
  DbtDagScriptsBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: bit-dbt-${self:provider.stage}
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: AllowMWAABucketAccess
            Effect: Allow
            Principal:
              AWS: !Sub "arn:aws:iam::${AWS::AccountId}:root"
            Action:
              - "s3:GetBucketLocation"
              - "s3:ListBucket"
            Resource:
              - !Sub "arn:aws:s3:::bit-dbt-${self:provider.stage}"
          - Sid: AllowMWAAObjectAccess
            Effect: Allow
            Principal:
              AWS: !Sub "arn:aws:iam::${AWS::AccountId}:root"
            Action:
              - "s3:GetObject"
              - "s3:GetObjectVersion"
            Resource:
              - !Sub "arn:aws:s3:::bit-dbt-${self:provider.stage}/*"
