steps:
  - block: "Choose deployment path"
    key: "choose-deploy-path"
    branches: "main"
    fields:
      - select: "Deployment path"
        key: "deploy_path"
        required: true
        options:
          - label: "Upload scripts to S3"
            value: "upload_s3"
          - label: "Deploy Serverless permissions"
            value: "serverless_permissions"
      - select: "Environment"
        key: "environment"
        required: true
        options:
          - label: "Development"
            value: "dev"
          - label: "Staging"
            value: "staging"
          - label: "Production"
            value: "prod"

  - label: ":pipeline: Route deployment"
    key: "route-deployment"
    depends_on: "choose-deploy-path"
    branches: "main"
    commands:
      - ".buildkite/route.sh"
